#cfitsio library path, library name
FITSPATH=-L/home/lnie/lib/ -L/home/lnie/anaconda3/lib/ 
FITSLIB=-lcfitsio -lpython3.9
FITSINCLUDE=-I/home/lnie/include
# general include path
INCLUDE=-I/usr/include/ -I/home/lnie/anaconda3/include/python3.9/

#include objects here:
objects= read_funcpsfs_new.o fits_IO.o nrutil.o creat_basisfs.o estimate_para.o fit_gaus.o\
		gasdev.o gaus_estimate.o indexx.o iSPCA_entr.o itoa.o k_sigma.o lubksb.o ludcmp.o moffat.o\
		 moffatlets.o mov_mer_ba.o PCA.o method_branches.o iSPCA.o SPCA_entr.o C_tools_lib.o\
		 ran1.o svdcmp.o rebasis.o star_ellip.o pythag.o linear_operation.o EMPCA.o EMPCA_entr.o\
		 interp_bicubic.o SPCA.o npsf.o coeff_interp.o size.o sort.o creat_star.o krig.o fof_source.o

objects1= read_funcpsfs_new.o fits_IO.o nrutil.o creat_basisfs.o estimate_para.o fit_gaus.o \
 gasdev.o gaus_estimate.o indexx.o iSPCA_entr.o itoa.o k_sigma.o lubksb.o ludcmp.o moffat.o\
 moffatlets.o mov_mer_ba.o PCA.o method_branches.o iSPCA.o SPCA_entr.o C_tools_lib.o\
 ran1.o svdcmp.o rebasis.o star_ellip.o pythag.o linear_operation.o EMPCA.o EMPCA_entr.o\
 interp_bicubic.o SPCA.o npsf.o coeff_interp.o size.o sort.o creat_star.o krig.o  fof_source.o

libpsffit.so:  $(objects) 
	cc -fPIC -g -O3 -o $@ $(objects) $(FITSPATH) $(FITSLIB) -shared -lm
# general compilation rules 

cut:  $(objects1) 
	cc -fPIC -g -O3 -o $@ $(objects1) $(FITSPATH) $(FITSLIB) -lm

.SUFFIXES:  .c   .o
.c.o:
	cc -fPIC -g -Wno-error -Wno-nullability-completeness -Wno-expansion-to-defined -Wno-builtin-requires-header -c $< -O3 -o $@ $(INCLUDE) $(FITSINCLUDE)
.PHONY:clean
clean:
	-rm libpsffit.so
	-rm ${objects}
	-rm ${cut}

